Repository neurobagel/query-tool, pull requests merged in 2024-04, with the labels that each got.

#93 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/handle_external_pr.yml
  LICENSE
Labels: _bot

#94 [MNT] Add dependabot.yml
  .github/dependabot.yml
Labels: _community, pr-internal

#97 [REF] Enable handling of partial node response success
  cypress/component/ResultContainer.cy.tsx
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Alert.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/e2e/Form.cy.ts
  cypress/e2e/ResultsTSV.cy.ts
  cypress/fixtures/mocked-responses.ts
  src/App.tsx
  src/components/ResultContainer.tsx
  src/utils/types.ts
Labels: pr-minor-breaking

#114 [CI] Set up docker nightly build
  .github/workflows/build_docker_nightly.yaml
  .github/workflows/deploy.yaml
  .lintstagedrc.json
  Dockerfile
Labels: pr-internal

#117 [FIX] Reverted back to installing devdependencies along with dependencies
  .github/workflows/deploy.yaml
  Dockerfile
Labels: skip-release

#120 [FIX] Updated deploy workflow config file
  .github/workflows/deploy.yaml
Labels: skip-release

#124 [FIX] Remove attributes with a NULL label
  cypress/e2e/APIRequests.cy.ts
  cypress/fixtures/mocked-responses.ts
  src/App.tsx
Labels: pr-bug-fix

#127 [CI] Add .github to .prettierignore
  .prettierignore
Labels: pr-internal

#115 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#126 [FIX] Fixed the condition for when federation API's `nodes_response_status` is `fail`
  cypress/fixtures/mocked-responses.ts
  src/App.tsx
  src/components/ResultContainer.tsx
Labels: release, pr-bug-fix

#139 [FIX] Hotfix for handling responses from n-API
  src/App.tsx
Labels: release, pr-bug-fix
