Repository neurobagel/query-tool, pull requests merged in 2024-03, with the labels that each got.

#39 [FIX] Fixed the performance issues caused by re-rendering
  src/components/ResultCard.tsx
  src/components/ResultContainer.tsx
Labels: pr-bug-fix

#44 [CI] Implement Prettier CI Check for Code Consistency
  .github/workflows/prettier.yaml
Labels: _community

#50 [CI] Set up GitHub pages deployment CI
  .github/workflows/deploy.yaml
Labels: pr-internal

#38 [MNT] Added post-merge hook and updated scripts
  .husky/post-merge
  .husky/pre-commit
  .lintstagedrc.json
  package.json
Labels: _community, pr-internal

#52 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/pull_request_template.md
  .github/workflows/add_iss2project.yml
  .github/workflows/build_docker_on_release.yml
  .github/workflows/release.yaml
  .github/workflows/stale.yml
Labels: _bot

#53 [MNT] Set the app version to `0.1.0` in package.json
  package.json
Labels: release, pr-internal

#83 [MNT] Add .prettierignore for CHANGELOG
  .prettierignore
Labels: pr-internal

#80 [CI] Remove GH variable dependence for tests
  .github/workflows/component-test.yaml
  .github/workflows/e2e-test.yaml
Labels: pr-internal

#86 [CI] adding codespell: fixing one typo
  .codespellrc
  .github/workflows/codespell.yml
  CHANGELOG.md
Labels: _community, pr-internal

#87 [MNT] Removed `corePlugins` option from `prettier` config file
  .prettierrc.json
Labels: pr-internal

#88 [FIX] Fixed parsing of `NB_IS_FEDERATION_API`
  src/components/QueryForm.tsx
  src/utils/constants.ts
Labels: pr-bug-fix

#91 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/stale.yml
Labels: _bot

#89 [DOC] Updated README.md
  README.md
Labels: pr-documentation

#92 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/handle_external_pr.yml
Labels: _bot
