Repository neurobagel/query-tool, pull requests merged in 2024-02, with the labels that each got.

#25 [FIX] Refactored synching of the `URLSearchParams` and selected nodes
  .github/workflows/e2e-test.yaml
  cypress.config.ts
  cypress.d.ts
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Alert.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/fixtures/mocked-responses.ts
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  src/App.tsx
  src/components/CategoricalField.tsx
  src/components/DownloadResultButton.tsx
  src/components/Navbar.tsx
  src/components/QueryForm.tsx
  src/components/ResultCard.tsx
  src/components/ResultContainer.tsx
  src/main.tsx
  src/utils/constants.ts
  vite.config.ts
Labels: pr-bug-fix

#30 [DOC] Update Copyright holders
  LICENSE
Labels: skip-release

#31 [MNT] Implemented component tests
  .github/workflows/component-test.yaml
  .gitignore
  cypress/component/CategoricalField.cy.tsx
  cypress/component/ContinuousField.cy.tsx
  cypress/component/DownloadResultButton.cy.tsx
  cypress/component/NBDialog.cy.tsx
  cypress/component/Navbar.cy.tsx
  cypress/component/QueryForm.cy.tsx
  cypress/component/ResultCard.cy.tsx
  cypress/component/ResultContainer.cy.tsx
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/e2e/Form.cy.ts
  cypress/e2e/ResultsTSV.cy.ts
  cypress/support/component.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/CategoricalField.tsx
  src/components/ContinuousField.tsx
  src/components/DownloadResultButton.tsx
  src/components/NBDialog.tsx
  src/components/Navbar.tsx
  src/components/QueryForm.tsx
  src/components/ResultCard.tsx
  src/components/ResultContainer.tsx
  src/utils/types.ts
Labels: pr-tests

#32 [ENH] Added Appzi widget
  index.html
Labels: pr-minor

#33 [MNT] Removed `CodeSee` workflow
  .github/workflows/codesee-arch-diagram.yml
Labels: skip-release

#35 [MNT] Added `prettier` support
  .husky/pre-commit
  .lintstagedrc.json
Labels: _community, pr-internal
