Repository neurobagel/query-tool, pull requests merged in 2024-12, with the labels that each got.

#380 [REF] Switch experimental auth to auth0
  cypress/component/AuthDialog.cy.tsx
  cypress/component/Navbar.cy.tsx
  cypress/e2e/Feedback.cy.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/AuthDialog.tsx
  src/components/Navbar.tsx
  src/main.tsx
  vite.config.ts
Labels: release, pr-internal

#390 [FIX] Replaced the latest version tag with a baked-in version
  .github/pull_request_template.md
  .github/workflows/build_docker_nightly.yml
  .github/workflows/bump_version.yml
  package.json
  src/components/Navbar.tsx
Labels: release, pr-bug-fix

#398 [ENH] Standardized query result files
  cypress/e2e/ResultsTSV.cy.ts
  src/components/ResultContainer.tsx
Labels: pr-patch

#396 [MNT] Refactored the `DownloadResultButton`
  cypress/component/DownloadResultButton.cy.tsx
  cypress/component/GetDataDialog.cy.tsx
  cypress/component/ResultContainer.cy.tsx
  cypress/e2e/ResultsTSV.cy.ts
  src/components/DownloadResultButton.tsx
  src/components/GetDataDialog.tsx
  src/components/ResultContainer.tsx
Labels: pr-patch

#400 [REF] Move appzi and plausible to the gh pages build
  .github/workflows/deploy.yaml
  index.html
Labels: pr-patch

#406 [MNT] Implemented error boundary
  package.json
  src/components/ErrorBoundary.tsx
  src/main.tsx
Labels: release, pr-minor

#412 [FIX] Fix deploy workflow
  .github/workflows/deploy.yaml
  index.html
Labels: pr-internal

#413 [MNT] Update labels in dependabot.yml
  .github/dependabot.yml
Labels: skip-release

#409 [ENH] Refined content and location of `How to access data` button
  cypress/component/QueryForm.cy.tsx
  cypress/component/ResultContainer.cy.tsx
  src/components/GetDataDialog.tsx
  src/components/QueryForm.tsx
  src/components/ResultContainer.tsx
Labels: pr-patch

#411 [ENH] Made dataset name hyperlink to dataset `PortalURI`
  cypress/component/ResultCard.cy.tsx
  src/components/ResultCard.tsx
  src/components/ResultContainer.tsx
Labels: pr-patch

#419 [MNT] Updated husky scripts
  .github/workflows/bump_version.yml
  .husky/post-merge
  .husky/pre-commit
  README.md
  package.json
Labels: release, pr-patch
