Repository neurobagel/query-tool, pull requests merged in 2024-07, with the labels that each got.

#205 [ENH] Implemented OIDC flow that results in a query sent to the f-API
  README.md
  cypress/component/AuthDialog.cy.tsx
  cypress/component/GetDataDialog.cy.tsx
  cypress/component/NBDialog.cy.tsx
  cypress/component/Navbar.cy.tsx
  cypress/component/ResultContainer.cy.tsx
  package-lock.json
  package.json
  src/App.tsx
  src/components/AuthDialog.tsx
  src/components/GetDataDialog.tsx
  src/components/Navbar.tsx
  src/components/ResultContainer.tsx
  src/main.tsx
  src/utils/constants.ts
  src/utils/types.ts
  vite.config.ts
Labels: pr-minor-breaking

#214 [ENH] Made authentication optional on the UI
  .github/workflows/e2e-test.yaml
  cypress/component/AuthDialog.cy.tsx
  cypress/component/Navbar.cy.tsx
  cypress/component/ResultContainer.cy.tsx
  cypress/e2e/Auth.cy.ts
  src/App.tsx
  src/components/AuthDialog.tsx
  src/components/Navbar.tsx
  src/components/ResultContainer.tsx
Labels: pr-minor

#217 🔄 synced file(s) with neurobagel/workflows
  .autorc
  .github/workflows/release.yaml
Labels: _bot
