Repository neurobagel/query-tool, pull requests merged in 2024-09, with the labels that each got.

#277 [FIX] Always prompt login if auth is enabled
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Alert.cy.ts
  cypress/e2e/Auth.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/e2e/Form.cy.ts
  cypress/e2e/ResultsTSV.cy.ts
  cypress/support/e2e.ts
  src/App.tsx
Labels: pr-minor

#288 [MNT] Revert `Bump @typescript-eslint/eslint-plugin from 7.16.1 to 8.6.0`
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  vite.config.ts
Labels: type:maintenance, maint:process

#289 [MNT] Bump @typescript-eslint/eslint-plugin from 7.16.1 to 8.6.0
  .eslintrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  vite.config.ts
Labels: pr-internal

#299 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_nightly.yml
Labels: _bot
