Repository neurobagel/query-tool, pull requests merged in 2024-10, with the labels that each got.

#292 [MNT] Removed build docker nightly workflow file
  .github/workflows/build_docker_nightly.yaml
Labels: pr-internal

#309 [MNT] Mocked API calls in `Auth` e2e test
  cypress/e2e/Auth.cy.ts
Labels: pr-tests

#323 [MNT] Fix badge link formatting in README.md
  README.md
Labels: skip-release

#322 [ENH] Implemented logic to allow for querying pipeline name and version
  cypress/component/QueryForm.cy.tsx
  cypress/component/ResultCard.cy.tsx
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Alert.cy.ts
  cypress/e2e/Auth.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/e2e/Form.cy.ts
  cypress/e2e/ResultsTSV.cy.ts
  cypress/fixtures/mocked-responses.ts
  src/App.tsx
  src/components/QueryForm.tsx
  src/components/ResultCard.tsx
  src/components/ResultContainer.tsx
  src/utils/constants.ts
  src/utils/types.ts
Labels: release, pr-minor-breaking

#325 [MNT] Created a complete test environment with docker compose
  .github/dependabot.yml
  .gitmodules
  .prettierignore
  README.md
  docker-compose.yml
Labels: pr-internal

#337 [MNT] Updated `pull_request_template` with check for `query-tool-results`
  .github/pull_request_template.md
Labels: skip-release

#336 [FIX] Implemented "no pipelines" button
  README.md
  cypress/component/ResultCard.cy.tsx
  src/components/ResultCard.tsx
Labels: pr-patch
