Repository neurobagel/query-tool, pull requests merged in 2024-08, with the labels that each got.

#235 [MNT] Removed trailing slash from `queryURL`
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Alert.cy.ts
  cypress/e2e/Checkbox.cy.ts
  cypress/e2e/ResultsTSV.cy.ts
  src/utils/constants.ts
Labels: release, pr-patch

#246 [REF] Renamed `NB_QUERY_URL_PATH` env var to `NB_QUERY_APP_BASE_PATH`
  README.md
  src/main.tsx
  src/utils/constants.ts
Labels: pr-internal

#245 [ENH] Removed `NB_IS_FEDERATION_API` environment variable
  .github/workflows/component-test.yaml
  .github/workflows/deploy.yaml
  .github/workflows/e2e-test.yaml
  README.md
  src/App.tsx
  src/components/QueryForm.tsx
  src/utils/constants.ts
Labels: release, pr-minor-breaking

#252 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#253 🔄 synced file(s) with neurobagel/workflows
  .github/workflows/build_docker_on_release.yml
Labels: _bot

#261 [ENH] Query tool ai UI integration
  package-lock.json
  package.json
  src/App.tsx
  src/components/Chatbot.tsx
  src/declarations.d.ts
  src/utils/constants.ts
  tsconfig.json
Labels: pr-minor
