Repository neurobagel/query-tool, pull requests merged in 2025-03, with the labels that each got.

#502 [FIX] Fix path for query tool result examples in `updated_examples.yaml`
  .github/workflows/updated_examples.yaml
Labels: skip-release

#504 [MNT] Update badge links in README.md
  README.md
Labels: skip-release, flag:check

#514 [MNT] Changed `Flow Weighted` label and name to `Functional MRI`
  cypress/e2e/ResultsTSV.cy.ts
  src/utils/constants.ts
Labels: pr-patch

#523 [REF] Revert to simple release workflow with post-release package.json bump
  .autorc
  .github/pull_request_template.md
  .github/workflows/build_docker_on_release.yml
  .github/workflows/bump_version.yml
Labels: release, pr-internal
