Repository neurobagel/query-tool, pull requests merged in 2025-01, with the labels that each got.

#435 [ENH] Add -u flag to dataget instruction
  src/components/GetDataDialog.tsx
Labels: pr-documentation

#432 [ENH] Implement Notification Icon with Badge for Warnings and Its Test
  cypress/component/Navbar.cy.tsx
  cypress/e2e/APIRequests.cy.ts
  src/App.tsx
  src/components/Navbar.tsx
  src/utils/types.ts
Labels: _community, pr-patch

#442 [ENH] Add singularity command switcher
  cypress/component/GetDataDialog.cy.tsx
  src/components/GetDataDialog.tsx
  vite.config.ts
Labels: pr-minor

#457 [ENH] making dataset hyperlinks more recognizable
  src/components/ResultCard.tsx
Labels: _community, pr-patch

#460 [CI] Updated `update_examples workflow` to run on `pull_request_target` event
  .github/workflows/updated_examples.yaml
Labels: pr-internal

#465 [CI] Updated `deploy` workflow to checkout with submodules
  .github/workflows/deploy.yaml
  package.json
Labels: release, pr-internal

#467 [FIX] Change internal port to 5173
  Dockerfile
Labels: release, pr-internal

#469 [FIX] Custom script addition in header
  .github/workflows/deploy.yaml
  index.html
  package.json
Labels: release, pr-internal
