Repository neurobagel/query-tool, pull requests merged in 2025-02, with the labels that each got.

#468 [DOC] Document NB_QUERY_HEADER_SCRIPT
  README.md
  entrypoint.sh
Labels: pr-documentation

#476 [ENH] Adjust form layout for small and tab screens
  cypress/e2e/Form.cy.ts
  src/App.tsx
Labels: _community, pr-patch

#484 [FIX] Stop appending trailing slash to f-API request
  src/App.tsx
Labels: pr-patch

#487 [FIX] Prevent previously selected pipeline version from appearing in the query after the field has been disabled
  cypress/e2e/APIRequests.cy.ts
  cypress/e2e/Form.cy.ts
  src/App.tsx
  src/components/QueryForm.tsx
Labels: pr-bug-fix
